spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/products/**
          filters:
            - RewritePath=/api/products/(?<segment>.*), /${segment}
        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /${segment}
        - id: cart-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/carts/**
          filters:
            - RewritePath=/api/carts/(?<segment>.*), /${segment}
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**
          filters:
            - RewritePath=/api/orders/(?<segment>.*), /${segment}

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
